name: test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'src/**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'src/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run build
      run: cargo build
    - name: Run clippy
      run: cargo clippy --all-targets --all-features --no-deps -- -D warnings
    - name: Run rustfmt
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test
