name: test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'src/**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'src/**.rs'

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.83.0
        components: clippy, rustfmt
    - name: Run build
      run: cargo build --locked
    - name: Run clippy
      run: cargo clippy --all-targets --all-features --no-deps -- -D warnings
    - name: Run rustfmt
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test
